"""Alembic environment — async engine, configuration from the app settings.

Runs migrations through the same asyncpg driver the application uses, so a
migration cannot succeed against a connection style the app cannot use.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from alembic import context
from app.core.config import settings

# Importing the models package registers every table on Base.metadata.
from app.db.session import Base
from app.models import *  # noqa: F403  (registers models for autogenerate)

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Credentials come from the environment, never from alembic.ini.
config.set_main_option("sqlalchemy.url", settings.database_url)

target_metadata = Base.metadata

# PostGIS and TimescaleDB create internal objects (spatial_ref_sys, Timescale's
# catalog schemas) that are not ours to manage. Excluding them keeps
# autogenerate from proposing to drop half the extension.
EXCLUDED_TABLES = {"spatial_ref_sys"}
EXCLUDED_SCHEMAS = {
    "tiger",
    "tiger_data",
    "topology",
    "_timescaledb_catalog",
    "_timescaledb_internal",
    "_timescaledb_config",
    "_timescaledb_cache",
    "timescaledb_information",
    "timescaledb_experimental",
}


def include_object(
    obj: object, name: str | None, type_: str, reflected: bool, compare_to: object
) -> bool:
    """Keep extension-owned objects out of autogenerated migrations."""
    if type_ == "table":
        schema = getattr(obj, "schema", None)
        if schema in EXCLUDED_SCHEMAS:
            return False
        if name in EXCLUDED_TABLES:
            return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout without a live database (`alembic upgrade --sql`)."""
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_object=include_object,
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations against a live async connection."""
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        # asyncpg caches prepared statements per connection; DDL that changes
        # types mid-migration can invalidate them.
        connect_args={"statement_cache_size": 0},
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
